services:
  mongo:
    image: mongo:latest
    container_name: animedle-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment: 
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
      MONGO_INITDB_DATABASE: animedle

  app:
    build: .
    container_name: animedle-app
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "5173:5173"
    depends_on:
      - mongo
    environment:
      - name=value

volumes:
  mongo_data:
