services:
  app-dev:
    build:
      context: .
      target: dev
    container_name: animedle-app
    restart: unless-stopped
    ports:
      - "3000:3000"
      - "5173:5173"
      - "3001:3001"
    depends_on:
      - mongo
    environment:
      - MONGODB_URL=mongodb://admin:adminpassword@mongo:27017/animedle?authSource=admin
      - FRONTEND_URL=http://localhost:5173

include:
  - docker-compose.yml
