services:
  app-prod-backend:
    build:
      context: .
      target: prod-backend
    container_name: animedle-app
    restart: unless-stopped
    ports:
      - "4445:3000"
    environment:
      - MONGODB_URL=${MONGODB_URL}
      - BETTER_AUTH_URL=${BACKEND_URL}
      - FRONTEND_URL=${FRONTEND_URL}
  
  app-prod-frontend:
    build:
      context: .
      target: prod-frontend
      args:
        - VITE_BACKEND_URL=${BACKEND_URL}
    container_name: animedle-frontend
    restart: unless-stopped
    ports:
      - "4444:80"
    